### ISSUE TITLE
Buffer error

### ISSUE THREAD

**Issue by SwaggerNiels** [dteal/gdsiistl#2]
Dear all,

The following error message pops up when i try to convert a gds file to stl:
```
Traceback (most recent call last):
  File "...\gdsiistl\gdsiistl.py", line 52, in <module>
    gdsii.read_gds(gdsii_file_path, units='import')
  File "...\Programs\Python\Python39\lib\site-packages\gdspy\library.py", line 2543, in read_gds
    for record in _record_reader(infile):
  File "...\Programs\Python\Python39\lib\site-packages\gdspy\gdsiiformat.py", line 80, in _record_reader
    struct.unpack(
struct.error: unpack requires a buffer of 616 bytes
```
I build my gds file in L-Edit, and this could be converted to stl for a while,
however now I get this error and its cause is unknown to me.

The number of bytes changes from time to time.

What could this mean, and how could this be resolved?

kind regards

**Comment by SwaggerNiels** [comment]
Apparently, this has something todo with L-Edit.
It can not produce gds files with this high number of vertices when I made an generated layer with some circular shapes.

This error in therefore means the gds file used is not correctly constructed.
